"""initial migration

Revision ID: 69866e257f87
Revises: 
Create Date: 2023-03-10 13:47:53.676908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69866e257f87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_table',
    sa.Column('activityId', sa.Integer(), nullable=False),
    sa.Column('activityType', sa.String(length=100), nullable=False),
    sa.Column('activityStartTime', sa.Time(), nullable=False),
    sa.Column('activityEndTime', sa.Time(), nullable=False),
    sa.Column('activityDay', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('activityId')
    )
    op.create_table('facility_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facilityName', sa.String(length=500), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('openingTime', sa.Time(), nullable=False),
    sa.Column('closingTime', sa.Time(), nullable=False),
    sa.Column('managerId', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_table',
    sa.Column('facilityID', sa.Integer(), nullable=False),
    sa.Column('activityID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activityID'], ['activity_table.activityId'], ),
    sa.ForeignKeyConstraint(['facilityID'], ['facility_table.id'], ),
    sa.PrimaryKeyConstraint('facilityID', 'activityID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    op.drop_table('facility_table')
    op.drop_table('activity_table')
    # ### end Alembic commands ###
