"""Added the facilitiesId attribute to the Booking table

Revision ID: bac672aa67c5
Revises: c29bcdbf3be4
Create Date: 2023-03-07 12:12:45.189924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac672aa67c5'
down_revision = 'c29bcdbf3be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('facilitiesId', sa.Integer(), nullable=False))
        batch_op.alter_column('createDate',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('bookingDate',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('bookingTime',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               nullable=False)
        batch_op.alter_column('bookingLength',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               nullable=False)
        batch_op.alter_column('bookingType',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('teamEvent',
               existing_type=sa.FLOAT(),
               type_=sa.Boolean(),
               nullable=False)
        batch_op.drop_index('ix_booking_userID')
        batch_op.drop_column('userID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userID', sa.VARCHAR(length=500), nullable=True))
        batch_op.create_index('ix_booking_userID', ['userID'], unique=False)
        batch_op.alter_column('teamEvent',
               existing_type=sa.Boolean(),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('bookingType',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('bookingLength',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('bookingTime',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('bookingDate',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('createDate',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('facilitiesId')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###
