"""Introduction of the Activities table

Revision ID: bbef96450b4e
Revises: 7785170c01f0
Create Date: 2023-03-07 18:53:08.451572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbef96450b4e'
down_revision = '7785170c01f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_table',
    sa.Column('activityId', sa.Integer(), nullable=False),
    sa.Column('activityType', sa.String(length=100), nullable=False),
    sa.Column('activityTimeDate', sa.DateTime(), nullable=False),
    sa.Column('activityDuration', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('activityId')
    )
    op.create_table('booking_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=500), nullable=False),
    sa.Column('facilitiesId', sa.Integer(), nullable=False),
    sa.Column('activityId', sa.Integer(), nullable=False),
    sa.Column('createDate', sa.Date(), nullable=False),
    sa.Column('bookingDate', sa.Date(), nullable=False),
    sa.Column('bookingTime', sa.Time(), nullable=False),
    sa.Column('bookingLength', sa.Time(), nullable=False),
    sa.Column('bookingEndTime', sa.Time(), nullable=False),
    sa.Column('bookingType', sa.String(length=500), nullable=False),
    sa.Column('teamEvent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activityId'], ['activity_table.activityId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_table')
    op.drop_table('activity_table')
    # ### end Alembic commands ###
