"""initial migration

Revision ID: c29bcdbf3be4
Revises: 
Create Date: 2023-02-20 22:09:04.274025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29bcdbf3be4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.String(length=500), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.Column('bookingDate', sa.DateTime(), nullable=True),
    sa.Column('bookingTime', sa.DateTime(), nullable=True),
    sa.Column('bookingLength', sa.DateTime(), nullable=True),
    sa.Column('bookingType', sa.String(length=500), nullable=True),
    sa.Column('teamEvent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_userID'), ['userID'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_userID'))

    op.drop_table('booking')
    # ### end Alembic commands ###
