"""Updated Activities table schema

Revision ID: ece47db39ef1
Revises: bbef96450b4e
Create Date: 2023-03-07 20:05:29.899295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece47db39ef1'
down_revision = 'bbef96450b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_table',
    sa.Column('activityId', sa.Integer(), nullable=False),
    sa.Column('activityType', sa.String(length=100), nullable=False),
    sa.Column('activityStartTime', sa.Time(), nullable=False),
    sa.Column('activityEndTime', sa.Time(), nullable=False),
    sa.Column('activityDay', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('activityId')
    )
    op.create_table('booking_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=500), nullable=False),
    sa.Column('facilitiesId', sa.Integer(), nullable=False),
    sa.Column('activityId', sa.Integer(), nullable=False),
    sa.Column('createDate', sa.Date(), nullable=False),
    sa.Column('bookingDate', sa.Date(), nullable=False),
    sa.Column('bookingTime', sa.Time(), nullable=False),
    sa.Column('bookingLength', sa.Time(), nullable=False),
    sa.Column('bookingEndTime', sa.Time(), nullable=False),
    sa.Column('bookingType', sa.String(length=500), nullable=False),
    sa.Column('teamEvent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activityId'], ['activity_table.activityId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_table')
    op.drop_table('activity_table')
    # ### end Alembic commands ###
