"""initial migration

Revision ID: f9db74897d3a
Revises: 
Create Date: 2023-02-23 16:19:30.344236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9db74897d3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facilityName', sa.String(length=500), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('openingTime', sa.Time(), nullable=False),
    sa.Column('closingTime', sa.Time(), nullable=False),
    sa.Column('managerId', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility')
    # ### end Alembic commands ###
